dist: trusty
sudo: required
language: node_js
node_js:
  - '16'
cache:
  directories:
    - node_modules
script:
  - yarn format
  - yarn lint
  - yarn test
after_success:
  - yarn coverage
  - cat coverage/lcov.info | npx coveralls
notifications:
  email:
    - dev-support@ampleforth.org
  slack: fragmentsorg:2bN0L0FCZZ0illBRyPucRZkV
